<?php

/**
 * StandardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StandardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return StandardTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Standard');
    }

    /**
     * @param $templateId
     * @param bool $criterionToExclude
     * @return mixed
     */
    public static function sumWeightByStandard($standardId, $criterionToExclude = false)
    {
      
        $query = Doctrine_Query::create()->select('s.id, SUM(s.weight) as total')->from('Standard s')->where('s.template_id = ?',
            $standardId);

        if ($criterionToExclude)
        {
            $query->andWhereNotIn('s.id', [$criterionToExclude]);
        }

        return $query->fetchOne()->getTotal();
    }

    Public function getAllCriteriasByTemplate($templateId, $hydrationMode = 2)
  {
    $query = Doctrine_Query::create()
      ->from('Standard s')
      ->where('s.template_id = ?', $templateId);

    return $query->fetchOne(null, $hydrationMode);
  }
}