<?php

/**
 * Standard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    check-list
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Standard extends BaseStandard
{

  public function getAllCriteriasByTemplate($templateId, $hydrationMode = 2)
  {
    return Doctrine_Core::getTable('Standard')->getAllCriteriasByTemplate($templateId, $hydrationMode);
  }

  public static function sumWeightByStandard($templateId, $criterionToExclude = false)
  {
    return Doctrine_Core::getTable('Standard')->sumWeightByStandard($templateId, $criterionToExclude);
  }

}