<?php

/**
 * Template
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    template
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Template extends BaseTemplate
{

    public function getTemplateById($templateId)
    {
        return Doctrine_Core::getTable('Template')
            ->getTemplateById($templateId);
    }
}
